# schema.yml

 version: 2
 
 sources:
   - name: raw
     schema: gz_raw_data
     tables:
       - name: sales
         identifier: raw_gz_sales
         description: sales of Greenweez / we have on row per product_id found in each orders_id
         loaded_at_field: "CAST(date_date AS TIMESTAMP)"
         freshness:
           warn_after: {count: 1, period: day}
         columns:
           - name: date_date
             description: date of purchase
           - name: orders_id
             description: id of thhe orders
           - name: products_id
             description: id of the products
           - name: revenue
             description: turnover
           - name: quantity
       - name: product
         identifier: raw_gz_product
         description: products of Greenweez
         columns:
         - name: products_id
           description: id of the products
           tests:
            - not_null
            - unique
         - name: purchSE_PRICE
           description: price of the purchase
       - name: ship
         identifier: raw_gz_ship
         description: sales of Greenweez / we have on row per product_id found in each orders_id
         columns:
          - name: orders_id
            description: id of the orders
            tests:
            - not_null
            - unique
          - name: shipping_fee
            description: cost of shipping tax
          - name: logcost
            description: logistic cost maybe ? 
          - name: ship_cost
            description: cost of shipping
       - name: adwords
         identifier: raw_gz_adwords
         description: detail marketing campaign on adwords
         columns:
           - name: date_date
             description: date
           - name: paid_source
             description: who was paid
           - name: campaign_key
             description: ...
           - name: camPGN_name
             description: name of the campaign
           - name: ads_cost
             description: costs for an ad
           - name: impression
             description: nb of impressions
           - name: click
             description: nb of clicks
             tests:
             - unique:
                column_name: "(date_date || '-'|| campaign_key)"
             - not_null:
                column_name: "(date_date || '-'|| campaign_key)"
       - name: facebook
         identifier: raw_gz_facebook
         description: detail marketing campaign on adwords
         columns:
           - name: date_date
             description: date
           - name: paid_source
             description: who was paid
           - name: campaign_key
             description: ...
           - name: camPGN_name
             description: name of the campaign
           - name: ads_cost
             description: costs for an ad
           - name: impression
             description: nb of impressions
           - name: click
             description: nb of clicks
             tests:
             - unique:
                column_name: "(date_date || '-'|| campaign_key)"
             - not_null:
                column_name: "(date_date || '-'|| campaign_key)"
       - name: bing
         identifier: raw_gz_bing
         description: detail marketing campaign on adwords
         columns:
           - name: date_date
             description: date
           - name: paid_source
             description: who was paid
           - name: campaign_key
             description: ...
           - name: camPGN_name
             description: name of the campaign
           - name: ads_cost
             description: costs for an ad
           - name: impression
             description: nb of impressions
           - name: click
             description: nb of clicks
             tests:
             - unique:
                column_name: "(date_date || '-'|| campaign_key)"
             - not_null:
                column_name: "(date_date || '-'|| campaign_key)"
       - name: criteo
         identifier: raw_gz_criteo
         description: detail marketing campaign on adwords
         columns:
           - name: date_date
             description: date
           - name: paid_source
             description: who was paid
           - name: campaign_key
             description: ...
           - name: camPGN_name
             description: name of the campaign
           - name: ads_cost
             description: costs for an ad
           - name: impression
             description: nb of impressions
           - name: click
             description: nb of clicks
             tests:
             - unique:
                column_name: "(date_date || '-'|| campaign_key)"
             - not_null:
                column_name: "(date_date || '-'|| campaign_key)"
       - name: finance_cmp_d
         identifier: finance_campaign_days
         description: ...
         columns:
           - name: date_date
             description: date
             tests:
             - unique
             - not_null
           - name: ads_margin
             description: ...
           - name: average_basket
             description: ...
           - name: operational_margin 
             description: ...
           - name: ads_cost 
             description: ...
           - name: ads_impressions
             description: ...
           - name: ads_click
             description: ...
           - name: quantity
             description: ...
           - name: revenue
             description: ...
           - name: purchase_cost
             description: ...
           - name:  margin
             description: ...
           - name: shipping_fee 
             description: ...
           - name: logcost
             description: ...
           - name: ship_cost
             description: ...
